### ISSUE TITLE
Not GoS winners, but would like to be considered

### ISSUE THREAD

**Issue by neurocis** [interchainio/delegation#1]
Just a request to be considered for delegation to even though piggy-coin.com validator was not a GoS winner. Many thanks in advance. 
cosmosvaloper1zp6kg7qlmztyw2km2af4z5ruz5vn04cp9npe79

**Comment by ebuchman** [comment]
Thanks for noting this. We are starting with a simple replicable process based on data available in the genesis block and on the blockchain for the first round of delegation.

We plan to revisit our strategy in the future to account for such cases, but can not make any guarantees.

**Comment by neurocis** [comment]
Thanks Ethan, nothing expected, merely a request for consideration. We (PIGGY) are represented in the genesis block however. Cheers!
