### ISSUE TITLE
01no.de GOS proof of address

### ISSUE THREAD

**Issue by clawmvp** [interchainio/delegation#10]
validator link: https://www.mintscan.io/validators/cosmosvaloper17mggn4znyeyg25wd7498qxl7r2jhgue8u4qjcq

validator address: cosmos17mggn4znyeyg25wd7498qxl7r2jhgue8ep585n
https://www.mintscan.io/txs/A18788E23697148C3CD6D5D7B926CAC58796E64945570360430A884F36055993
gos address: cosmos1wf3sncgk7s2ykamrhy4etf09y94rrrg43cdad7
https://www.mintscan.io/txs/8d816afaf238a77619210a04cf7a29ed6dc564ef22d3b676c15930762d798288

**Comment by ebuchman** [comment]
Looks like the two linked txs are the same. Do you have a second tx from the cosmos1wf3sncgk7s2ykamrhy4etf09y94rrrg43cdad7 account that includes the cosmos17mggn4znyeyg25wd7498qxl7r2jhgue8ep585n in the memo?

**Comment by clawmvp** [comment]
oh, sorry for that, this one:

https://www.mintscan.io/txs/8d816afaf238a77619210a04cf7a29ed6dc564ef22d3b676c15930762d798288

i also edited the initial post with the correct link.

**Comment by ebuchman** [comment]
Thanks

**Comment by ebuchman** [comment]
Done: https://stargazer.certus.one/transactions/341481:8E66AE7ED2DABFAC3D690920DFD681A9C68495E784C3F6D783B0A206294DBB0C
