### ISSUE TITLE
stake.zone - proof of addresses

### ISSUE THREAD

**Issue by nuevax** [interchainio/delegation#11]
validator link: https://www.mintscan.io/validators/cosmosvaloper1rfpar0qx3umnhu0f6wjp4hvnr3x6u5389e094j

validator address: cosmos1rfpar0qx3umnhu0f6wjp4hvnr3x6u538qdmsep
https://www.mintscan.io/txs/A3E4DE6E03C04CA3D39DCB1E3FA03B23C64CBA84DB6ABBC84C0868B92D8C0ADE

GoS address: cosmos199843dmw5r4nkt6ld00y0wdm0rnnwump4lgs30
https://www.mintscan.io/txs/3E434C198935B8A56F050AA52B3F92E021F0A36B04D46DA05FC6D40A6BC5FFD1

**Comment by ebuchman** [comment]
Done https://stargazer.certus.one/transactions/341481:8E66AE7ED2DABFAC3D690920DFD681A9C68495E784C3F6D783B0A206294DBB0C
