### ISSUE TITLE
CoinoneNode - Proof of ownership of Addresses (GoS & Fundraiser)

### ISSUE THREAD

**Issue by ghost** [interchainio/delegation#13]
CoinoneNode validator link: 
https://www.mintscan.io/validators/cosmosvaloper1te8nxpc2myjfrhaty0dnzdhs5ahdh5agzuym9v

validator address: ' cosmos1te8nxpc2myjfrhaty0dnzdhs5ahdh5ag8gswfl '
https://www.mintscan.io/txs/6BF79CF65D0D269DE9245B6A0B4FFFE627DDF7E35098F5137BFA0737F10B2244

GoS address: ' cosmos1pz6yu5vdxfzw85cn6d7rp52me4lu8khx7lpkzd '
https://www.mintscan.io/txs/D0A4146A853D3244277B4D28F63AA28111CFC8ADE7FC99470CC6E922855ABC1E

**Comment by ebuchman** [comment]
Thanks.

According to what's outlined in https://github.com/interchainio/delegation#delegating-to-gos-winners, to be eligible for this round of delegation, you must have delegated at least 50% of the GoS winnings to your validator.

It looks like all the GoS winnings were actually delegated to Sikka, and only 1 atom from the fundraiser address was delegated to your validator. Are we missing something?

**Comment by ghost** [comment]
Hi Ethan. This is Team CoinoneNode. 
Let me clarify this situation. With GoS winnings, we wanted to test all functions on the mainnet such as delegation, unbonding etc. Now, our GoS winnings is being unbonded and only 1 day left to complete unbonding. Once our GoS winnings get unbonded tomorrow, we will delegate to our new validator account by tomorrow. You will be able to check our GoS winnings delegated to our new validator tomorrow. Thank you.

**Comment by ghost** [comment]
@ebuchman 
We, CoinoneNode just delegated our GoS winnings(5000 ATOM) to our validator.
You can check it from the link below. Thanks.  
https://www.mintscan.io/txs/81397342cd92148dde6a8e7dcf708eab5ce4f37eea37fb0f3287bb0ca611d1b6

**Comment by ebuchman** [comment]
Awesome thanks

**Comment by ghost** [comment]
@ebuchman Thanks for confirming. When are you planning to delegate if I may ask?

**Comment by ebuchman** [comment]
Done. https://stargazer.certus.one/transactions/341481:8E66AE7ED2DABFAC3D690920DFD681A9C68495E784C3F6D783B0A206294DBB0C

**Comment by ghost** [comment]
Hi! This is Coinone Node. I have a question regarding ICF delegation. Please shoot me an email

node@coinone.com
@ebuchman
