### ISSUE TITLE
Created a new account for a validator service

### ISSUE THREAD

**Issue by ghost** [interchainio/delegation#2]
After GoS, we have created a new account and have been running the new account for our validator service. If we are eligible for ICF ATOM delegation, we would like to get ICF ATOM delegation to our new account. 

The account participated in GoS (Inactive now) 
" cosmos1pz6yu5vdxfzw85cn6d7rp52me4lu8khx7lpkzd "

The new account currently running for a validator service
" cosmos1te8nxpc2myjfrhaty0dnzdhs5ahdh5ag8gswfl "

Thank you.

**Comment by ebuchman** [comment]
Thanks for noting this. We are starting with a simple replicable process based on data available in the genesis block and on the blockchain for the first round of delegation.

We plan to revisit our strategy in the future to account for such cases, but can not make any guarantees.

**Comment by ebuchman** [comment]
Please see https://github.com/interchainio/delegation#gos-winners-using-non-gos-validator-addresses
