### ISSUE TITLE
Chinezupwnz evolved to group as Easy 2 Stake, GoS proof of ownership

### ISSUE THREAD

**Issue by chinezupwnz** [interchainio/delegation#29]
Hello ICF,

Unfortunately, i wasn't able to participate from the start due to a misfortunate series of personal problems. My infra is ready now and would kindly ask if i can still get support from ICF.
I have 100% of GoS winnings delegated.

Validator
https://www.mintscan.io/validators/cosmosvaloper1e0plfg475phrsvrlzw8gwppeva0zk5yg9fgg8c

Validator address
cosmos1e0plfg475phrsvrlzw8gwppeva0zk5ygqauatt

GoS genesis address (w/ memo)
https://www.mintscan.io/txs/E67028CC10DC8AD7CC6B977E489A0E1757A3B5C10F1FD7C166554C42217E5428

Thank you,
Liviu

**Comment by StakerSpace** [comment]
Looks like a very luxurious problem,  knowing you had GOS winnings and don't use that for your own validator. anyways I actually openend this repo for the same reason. Will there be a third batch of ICF delegation or is it from here a free market ?

**Comment by ebuchman** [comment]
It looks like all your atoms are delegated, but not to your validator. The rules require that the GoS winnings be delegated to your own validator to be eligible for the ICF delegation. Is there some reason the cosmos1399zgcq58j20jth3r0hnjq2lswem60jmjs7u36 account (ie. the GoS winner) delegated its Atoms to cosmosvaloper19j2hd230c3hw6ds843yu8akc0xgvdvyuz9v02v (ie. syncnode) instead of cosmosvaloper1e0plfg475phrsvrlzw8gwppeva0zk5yg9fgg8c (ie. your validator) ?

**Comment by chinezupwnz** [comment]
Hello Ethan. First of all thank you for responding to my inquiry.
Please check the following TX of delegation to easy 2 stake from GoS account https://www.mintscan.io/txs/5c264ed8d0a2181aafbd0ef5f358aae95652fdbb449418c98f64c74083917813
Because of the delay that i had with being ready with infra, i took a decision to delegate to syncnode. Nevertheless the atoms did not leave the cosmos eco system and as you can see Easy 2 Stake has an amount of over 3500 atoms bought from the exchanges proving our involvement in cosmos and dedication. Easy2Stake will continue to ramp up on every aspect on Cosmo Network. 
With the help of ICF we can move forward and thus investing more effort in Cosmos network.
Thank you,
Liviu

**Comment by ebuchman** [comment]
Done, thanks for your patience: https://www.mintscan.io/txs/E4F0F0EA6900DD7B397AC4A2B1913AF173F05C4FFA8C3C0E8E05A9BC340C3235
