### ISSUE TITLE
diffrent validator account

### ISSUE THREAD

**Issue by clawmvp** [interchainio/delegation#3]
hello, i m one of the winners of GOS but also a participant at fundraiser, and i created my validator with the fundraiser account, i m still eligible for delegation?

**Comment by ebuchman** [comment]
Thanks for noting this. We are starting with a simple replicable process based on data available in the genesis block and on the blockchain for the first round of delegation.

We plan to revisit our strategy in the future to account for such cases, but can not make any guarantees.

**Comment by clawmvp** [comment]
There is something i can or must do for my particular case?

**Comment by nuevax** [comment]
I have the same issue, participated in GoS and got the 5k, but delegated all Atoms from the GoS address cosmos199843dmw5r4nkt6ld00y0wdm0rnnwump4lgs30 to a validator assigned to the GoS moniker set up with a fundraiser account, https://hubble.figment.network/chains/cosmoshub-1/validators/064CF05857B556FED63AC32821FF904312D0F2C8 .

**Comment by ebuchman** [comment]
Please see https://github.com/interchainio/delegation#gos-winners-using-non-gos-validator-addresses
