### ISSUE TITLE
No Commission Criteria

### ISSUE THREAD

**Issue by fkbenjamin** [interchainio/delegation#4]
Not intended as an issue, but rather a question/suggestion: 
I would suggest a maximum commission in the delegation criteria. They way it is right now I could bond 51% of my GoS ATOM to a new validator, set the commission rate to 100% and would be eligible for a delegation up to 1M ATOM. I'm sure this is not the intention behind this and would love to hear what the foundation is thinking about that.

**Comment by ebuchman** [comment]
We felt we would start simple and trust that validators would act in good faith re their commission and the need to attract additional delegators beyond the ICF. If we find validators start taking advantage of ICF delegations by jacking their commission, we may adjust the criteria accordingly and undelegate/redelegate from them.

**Comment by ebuchman** [comment]
Closing this for now. The ICF will continue to trust validators to remain competitive in their commission rates, and will continue to monitor and adjust its delegation strategy as necessary.

**Comment by fkbenjamin** [comment]
Meanwhile, the case described above has arrived and a validator charged 100% commission on his foundation delegation. 
You can find a discussion about it on twitter: https://twitter.com/bigdipperlive/status/1136553573930508290

Here is the link to the validator:
https://cosmos.bigdipper.live/validator/cosmosvaloper1rcp29q3hpd246n6qak7jluqep4v006cdsc2kkl

Is the foundation still trusting validators to remain competitive when a 100% fee delegation from the foundation can be more profitable than being in the top 20 of all validators? Could we please open this issue again and discuss a way to make this process better and more transparent?

**Comment by iammelea** [comment]
Sir, I like to know,
Why ICF decided not to support my validator in any way.?

https://hubble.figment.network/cosmos/chains/cosmoshub-2/validators/51DB2566204EE266427EA8A6CB719835AB170BE9

if it is to prove "skin in the game", I can leave the rewards blocked and compound these for two years. then release 10% each month from month 25 for example, if was necessary.

if the foundation is afraid of slashed by double signature, in my current setup it is impossible.

If you are afraid of slashed by downtime, comment that my time is good and if I have to improve it, I can do it too.

open to suggestions if any.
ty in advanced.

**Comment by ariannef** [comment]
> Meanwhile, the case described above has arrived and a validator charged 100% commission on his foundation delegation.
> You can find a discussion about it on twitter: https://twitter.com/bigdipperlive/status/1136553573930508290
> 
> Here is the link to the validator:
> https://cosmos.bigdipper.live/validator/cosmosvaloper1rcp29q3hpd246n6qak7jluqep4v006cdsc2kkl
> 
> Is the foundation still trusting validators to remain competitive when a 100% fee delegation from the foundation can be more profitable than being in the top 20 of all validators? Could we please open this issue again and discuss a way to make this process better and more transparent?

Moving forward we plan to ensure commission rate is factored into delegation criteria. After evaluating validator behaviour, we feel this is an important consideration. We will be issuing a strategy for the next round of delegations shortly. The ICF aims for delegations to always be fair, transparent and go to validators who are contributing to the Cosmos Network in positive ways.

**Comment by ariannef** [comment]
After further investigation in to this validator and looking into their rebate program, we have reached out to them individually to clarify this. The ICF plans to review and redelegate as needed during the next round of delegations.

**Comment by fkbenjamin** [comment]
Thanks for having a look, ICF! Seems this is finally resolved now and can be closed.
