### ISSUE TITLE
A big effort for nothing?

### ISSUE THREAD

**Issue by wimel** [interchainio/delegation#5]
What about those of us who have been involved in the project for a long time, we've been in GoS from the first version to the last one and we haven't been considered?
We didn't receive an email or response from the team, but we've been trying to help the project as best we can.
Not only in GoS, in previous testnets we have been present.

**Comment by ebuchman** [comment]
Thanks for noting this. We are starting with a simple replicable process based on data available in the genesis block and on the blockchain for the first round of delegation.

We plan to revisit our strategy in the future to account for such cases, but can not make any guarantees.

**Comment by StakerSpace** [comment]
@ebuchman 

I was active in GoS with the same address as I am [validator](https://www.mintscan.io/validators/cosmosvaloper1crf28v52ptkygcw07kr79rw8dme7v2m2sy0p0p) right now. It's a good effort from the ICF to find balance in the chain, so it doesn't get centralized. 

The people that get admitted to the genesis where the "winners" of GoS and that were there becasue of metric of succes had to be maintained. I think the best way of governance is to also note when to make the exception. 

When GoS was just about to start, I wanted to upgrade my servers and thought the mnenomic/seed would be enough to recover everything. The priv_validator that I signed the gentx file with was just as important. When it got live I started precommiting empty blocks and got jailed numerous times in a row, until I found out what was happening, not the smartest thing to do as the total missed precommits is what worked against me in the results

In it's essence being a winner in GoS was just mainly being up and always updating your nodes when the new rounds started. There were many other strategies, but as long as you followed the recipe you could have been added to the list of winners. 

In the last round (6), StakerSpace was in the top 10 of pre-commits, for someone that just missed 100K blocks, that isn't a bad succes metric I would say, as round 6 was pretty stormy. 

I had numerous talks with Zaki about being let into the genesis, he advised against based on this total outlook on the results. I am looking forward to a different perspective from the ICF. I eventually got kick-started by Cryptium Labs, which is a real nice gesture from them.

All in All, #CosmosLaunch was awesome!

**Comment by wimel** [comment]
@ebuchman I don't think this answers my question, after the number of hours dedicated to the project that doesn't take into consideration the participants for no apparent reason, it doesn't make sense.
It is a pity that after all this work this is the result.
I think they should take more care of the community that is really supporting the project from the beginning.

**Comment by ebuchman** [comment]
Hi folks, thanks for the details, and for your dedication to and support of the project. We really do appreciate it!

Please note that this isn't the be all end all of ICF delegation. We are just getting started with something simple until we have more time to evaluate alternative strategies. Please bear with us - we hope to have some updates in this regard soon.

Thanks for your patience and continued support!

**Comment by StakerSpace** [comment]
@ebuchman 
Thanks for your hopeful answer, as the tokens are not transferable and also the community is keeping each other bonded based on reputation, meet-ups/parties and GoS. It's really hard to come in to this without breaking the bank (once transferable). 

It would be great if the ICF could delegate until the tokens are transferable, which might lead to more centralization, if they smaller validators don't propose any blocks. Anyway Looking forward to some updates soon.

**Comment by ebuchman** [comment]
Please see the [latest delegation](https://github.com/interchainio/delegation/tree/master/delegations/2-match-small), which included all validators with less than 250k ATOMs. 

Let's close this issue for now. If you have more thoughts or recommendations, please feel free to open another issue.
