### ISSUE TITLE
after your selective delegation to only some validator more centralization.

### ISSUE THREAD

**Issue by iammelea** [interchainio/delegation#6]
after your selective delegation to only some validator = more centralization.

Imo delegate in this way is not healthy for a Cosmos long term decentralization.

what did I see then?

more centralization and its look like the Foundation is going to have some validator army or group and this validator that is not going to be free mind or mouth because have a fear that the foundation reverses the delegation and this validator gets unemployed.  

**for being clear I can be a choice for this delegation**, only have to delegate the 50% of atoms won in Gos, anyway, I don't look for an employed from the delegation after they delegate to my node, I am looking for a decentralized cosmos network. just that. 

of course, I want to be validator in cosmos, but at the end of the day I want to be proud of my validator job, after see how Atoms holders delegate to my node and make me a validator, not because i autodelgate to my self or my group of friends a bucnh of atoms. 

I am not a dev, but imo the centralization can be fixed but in the code, not dropping more delegation to a centralized system.

**Comment by ebuchman** [comment]
Thanks for the thoughts Melea. 

Please note that this isn't the be all end all of ICF delegation. We are just getting started with something simple until we have more time to evaluate alternative strategies. 

If you have concrete suggestions, we'd be happy to hear them :)

**Comment by ebuchman** [comment]
Please see the [latest delegation](https://github.com/interchainio/delegation/tree/master/delegations/2-match-small), which included all validators with less than 250k ATOMs. 

Let's close this issue for now. If you have more thoughts or recommendations, please feel free to open another issue.
