### ISSUE TITLE
GoS and further decentralization

### ISSUE THREAD

**Issue by StakerSpace** [interchainio/delegation#8]
I left a comment in #5 ,which isn't addressed yet. My story is  [here](https://github.com/interchainio/delegation/issues/5#issuecomment-475394022)

Furthermore wanted to address that many GoS winners also were a part of the ICO for Cosmos. It just shows how on top things they were and that is great commitement to cosmos. but it leads to more centralization and the top validators keeping each other bonded. 

It would be great if the ICF  recognizes this and also show some love for the smaller validators that didn't get rewarded by GoS, but are validating at the moment

**Comment by ebuchman** [comment]
Please see the comment in https://github.com/interchainio/delegation/issues/5#issuecomment-476397485
